language: r
sudo: true
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      r: oldrel
      r_binary_packages:
        - devtools
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - _R_CHECK_FORCE_SUGGESTS_=false
    - os: linux
      dist: trusty
      r: release
      r_binary_packages:
        - devtools
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - _R_CHECK_FORCE_SUGGESTS_=false
    - os: linux
      dist: trusty
      r: devel
      r_binary_packages:
        - devtools
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update -q
  - sudo apt-get install r-cran-rjags -y
  - mkdir -p ~/.R/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars; fi

